question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Humans can distinguish between over a trillion different smells.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Bees are found everywhere in the world except Antarctica.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "The shortest war in history was between England and Zanzibar on 27 August 1896. Zanzibar surrendered after 38 minutes.", "answer": "True"},
    {"text": "A group of flamingos is called a 'pat'.", "answer": "False"},
    {"text": "Polar bears have black skin.", "answer": "True"},
    {"text": "There are 14 bones in the human face.", "answer": "True"},
    {"text": "Pineapples grow in the ground.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "You can sneeze in your sleep.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The longest recorded flight of a chicken is 13 seconds.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "There are more public libraries in the US than McDonald's restaurants.", "answer": "True"},
    {"text": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"text": "The human nose can detect a trillion smells.", "answer": "True"},
    {"text": "An adult human body has 206 bones.", "answer": "True"},
    {"text": "There are more cells of bacteria in your body than there are human cells.", "answer": "True"},
    {"text": "A human can survive underwater without any breathing equipment.", "answer": "False"},
    {"text": "A human can live without a gallbladder.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "It takes 8 minutes and 20 seconds for light from the Sun to reach Earth.", "answer": "True"},
    {"text": "The capital city of Australia is Sydney.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain on Earth.", "answer": "True"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "The Sahara is the largest desert in the world.", "answer": "False"},
    {"text": "The currency of Japan is the Yen.", "answer": "True"},
    {"text": "Albert Einstein was awarded the Nobel Prize in Physics.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Water boils at 90 degrees Celsius.", "answer": "False"},
    {"text": "The human skeleton renews itself completely every 10 years.", "answer": "True"},
    {"text": "Venus is the only planet that rotates clockwise.", "answer": "True"},
    {"text": "A day on Jupiter is shorter than a day on Earth.", "answer": "True"},
    {"text": "A leap year has 366 days.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The blue whale is the largest animal ever to have lived.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"text": "The first person to walk on the moon was Neil Armstrong.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The human brain is the heaviest organ in the human body.", "answer": "False"},
    {"text": "Lightning is hotter than the surface of the sun.", "answer": "True"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "The Grand Canyon is located in Nevada.", "answer": "False"},
    {"text": "There are 9 planets in the solar system.", "answer": "False"},
    {"text": "Diamonds are the hardest natural substance on Earth.", "answer": "True"},
    {"text": "The chemical symbol for gold is Ag.", "answer": "False"},
    {"text": "The Great Wall of China is more than 20,000 kilometers long.", "answer": "True"},
    {"text": "The capital of Italy is Rome.", "answer": "True"},
    {"text": "Humans and dinosaurs coexisted.", "answer": "False"},
    {"text": "The boiling point of water is 100 degrees Fahrenheit.", "answer": "False"},
    {"text": "The smallest bone in the human body is in the ear.", "answer": "True"},
    {"text": "The study of weather is called meteorology.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The capital of France is Paris.", "answer": "True"},
    {"text": "The human eye can distinguish about 10 million different colors.", "answer": "True"},
    {"text": "There are seven continents in the world.", "answer": "True"},
    {"text": "The Sun is a star.", "answer": "True"},
    {"text": "Water is made up of three atoms.", "answer": "True"},
    {"text": "The speed of light is approximately 300,000 kilometers per second.", "answer": "True"},
    {"text": "A group of jellyfish is known as a bloom.", "answer": "True"},
    {"text": "The Great Wall of China is made of ice.", "answer": "False"},
    {"text": "Earth is the third planet from the Sun.", "answer": "True"},
    {"text": "Sharks are fish.", "answer": "True"},
    {"text": "The smallest country in the world is Vatican City.", "answer": "True"},
    {"text": "The largest country in the world by land area is Russia.", "answer": "True"},
    {"text": "The fastest land animal is the cheetah.", "answer": "True"},
    {"text": "A group of lions is known as a pride.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "The tallest building in the world is located in New York City.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "A caterpillar turns into a butterfly.", "answer": "True"},
    {"text": "The capital of Brazil is Rio de Janeiro.", "answer": "False"},
    {"text": "The freezing point of water is 32 degrees Celsius.", "answer": "False"},
    {"text": "The Amazon rainforest is located in Africa.", "answer": "False"},
    {"text": "The Statue of Liberty was a gift from France.", "answer": "True"},
    {"text": "Mount Kilimanjaro is the highest mountain in Africa.", "answer": "True"},
    {"text": "Bats are mammals.", "answer": "True"},
    {"text": "The capital of India is Mumbai.", "answer": "False"},
    {"text": "A group of crows is known as a murder.", "answer": "True"},
    {"text": "The longest river in the world is the Nile River.", "answer": "True"},
    {"text": "Elephants are the largest land animals.", "answer": "True"},
    {"text": "J.K. Rowling wrote the Harry Potter series.", "answer": "True"},
    {"text": "Mars is also known as the Red Planet.", "answer": "True"},
    {"text": "The currency of the United Kingdom is the Euro.", "answer": "False"},
    {"text": "The capital of China is Shanghai.", "answer": "False"},
    {"text": "The Taj Mahal is located in India.", "answer": "True"},
    {"text": "The chemical symbol for oxygen is O2.", "answer": "False"},
    {"text": "The largest ocean on Earth is the Pacific Ocean.", "answer": "True"},
    {"text": "Australia is both a country and a continent.", "answer": "True"},
    {"text": "The capital of Japan is Tokyo.", "answer": "True"},
    {"text": "The human heart has four chambers.", "answer": "True"},
    {"text": "The capital of Russia is Moscow.", "answer": "True"},
    {"text": "A triangle has three sides.", "answer": "True"},
    {"text": "The longest bone in the human body is the femur.", "answer": "True"},
    {"text": "Sharks have bones.", "answer": "False"},
    {"text": "The largest mammal in the world is the elephant.", "answer": "False"},
    {"text": "Mercury is the closest planet to the Sun.", "answer": "True"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "The capital of Germany is Berlin.", "answer": "True"},
    {"text": "The Moon is a planet.", "answer": "False"},
    {"text": "Humans have more than two senses.", "answer": "True"},
    {"text": "The capital of South Korea is Seoul.", "answer": "True"},
    {"text": "Saturn is known for its ring system.", "answer": "True"},
    {"text": "The Great Wall of China is located in Japan.", "answer": "False"},
    {"text": "The chemical symbol for water is H2O.", "answer": "True"},
    {"text": "Mount Everest is located in the Himalayas.", "answer": "True"},
    {"text": "The capital of Spain is Barcelona.", "answer": "False"},
    {"text": "A year on Earth is 365 days long.", "answer": "True"},
    {"text": "Fish cannot drown in water.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The largest continent by land area is Africa.", "answer": "False"},
    {"text": "The Amazon River is the second longest river in the world.", "answer": "True"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"},
    {"text": "A group of dolphins is called a pod.", "answer": "True"},
    {"text": "The human body has 5 senses.", "answer": "False"},
    {"text": "The chemical symbol for helium is He.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "A heptagon has eight sides.", "answer": "False"},
    {"text": "The largest ocean on Earth is the Atlantic Ocean.", "answer": "False"},
    {"text": "Humans can breathe underwater without any equipment.", "answer": "False"},
    {"text": "The human brain is fully developed at birth.", "answer": "False"},
    {"text": "The Eiffel Tower is located in Paris.", "answer": "True"},
    {"text": "The capital of Thailand is Bangkok.", "answer": "True"},
    {"text": "Mars has two moons.", "answer": "True"},
    {"text": "The currency of the United States is the Dollar.", "answer": "True"},
    {"text": "The longest river in Asia is the Yangtze River.", "answer": "True"},
    {"text": "The human body has 12 pairs of ribs.", "answer": "True"},
    {"text": "The capital of Italy is Venice.", "answer": "False"},
    {"text": "The currency of Germany is the Franc.", "answer": "False"},
    {"text": "A triangle has four sides.", "answer": "False"},
    {"text": "The Pacific Ocean is located to the west of the United States.", "answer": "True"},
    {"text": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"text": "The largest country in South America is Argentina.", "answer": "False"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "The human body has more than 200 bones.", "answer": "True"},
    {"text": "The Amazon rainforest is located in South America.", "answer": "True"},
    {"text": "The capital of Russia is St. Petersburg.", "answer": "False"},
    {"text": "Humans can see ultraviolet light.", "answer": "False"},
    {"text": "The capital of Egypt is Alexandria.", "answer": "False"},
    {"text": "A decagon has ten sides.", "answer": "True"},
    {"text": "The currency of Japan is the Yen.", "answer": "True"},
    {"text": "The tallest mountain in the world is K2.", "answer": "False"},
    {"text": "The capital of France is Rome.", "answer": "False"},
    {"text": "The Amazon River is located in Asia.", "answer": "False"},
    {"text": "The chemical symbol for carbon is C.", "answer": "True"},
    {"text": "The capital of India is New Delhi.", "answer": "True"},
    {"text": "The human heart is on the left side of the body.", "answer": "False"},
    {"text": "The Great Barrier Reef is located off the coast of Australia.", "answer": "True"},
    {"text": "The capital of South Korea is Beijing.", "answer": "False"},
    {"text": "The currency of China is the Yen.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The longest river in Europe is the Volga River.", "answer": "True"},
    {"text": "A group of sheep is called a flock.", "answer": "True"},
    {"text": "The capital of Brazil is São Paulo.", "answer": "False"},
    {"text": "The human brain is made up of more than 100 billion neurons.", "answer": "True"},
    {"text": "The largest country in the world by population is China.", "answer": "True"},
    {"text": "The capital of the United States is Washington, D.C.", "answer": "True"},
    {"text": "The chemical symbol for hydrogen is H.", "answer": "True"},
    {"text": "The human body has two kidneys.", "answer": "True"},
    {"text": "The capital of Italy is Paris.", "answer": "False"},
    {"text": "The Sahara Desert is the largest desert in the world.", "answer": "False"},
    {"text": "The currency of France is the Franc.", "answer": "False"},
    {"text": "The capital of Germany is Berlin.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The tallest building in the world is in Dubai.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "The largest ocean on Earth is the Pacific Ocean.", "answer": "True"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The Great Wall of China is made of brick.", "answer": "True"},
    {"text": "The capital of Japan is Tokyo.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The capital of Russia is Moscow.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "The Great Barrier Reef is located in the Indian Ocean.", "answer": "False"},
    {"text": "The tallest mountain in the world is Mount Everest.", "answer": "True"},
    {"text": "The chemical symbol for water is H2O.", "answer": "True"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"},
    {"text": "The human body has 12 pairs of ribs.", "answer": "True"},
    {"text": "The Eiffel Tower is located in London.", "answer": "False"},
    {"text": "The Great Wall of China is located in China.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The largest continent by land area is Africa.", "answer": "False"},
    {"text": "The capital of Australia is Canberra.", "answer": "True"},
    {"text": "The Amazon rainforest is located in South America.", "answer": "True"},
    {"text": "The capital of Egypt is Alexandria.", "answer": "False"},
    {"text": "The smallest country in the world is Vatican City.", "answer": "True"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The tallest building in the world is in New York City.", "answer": "False"},
    {"text": "The capital of Japan is Osaka.", "answer": "False"},
    {"text": "The Great Barrier Reef is located off the coast of Australia.", "answer": "True"},
    {"text": "The chemical symbol for carbon is C.", "answer": "True"},
    {"text": "The largest country in the world by land area is Canada.", "answer": "False"},
    {"text": "The capital of South Korea is Seoul.", "answer": "True"},
    {"text": "The Great Wall of China is made of ice.", "answer": "False"},
    {"text": "The capital of France is Paris.", "answer": "True"},
    {"text": "The Sahara Desert is the largest desert in the world.", "answer": "False"},
    {"text": "The currency of China is the Yuan.", "answer": "True"},
    {"text": "The human body has 32 teeth.", "answer": "True"},
    {"text": "The Great Wall of China is located in Japan.", "answer": "False"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The capital of Italy is Rome.", "answer": "True"},
    {"text": "The human brain has over 100 billion neurons.", "answer": "True"},
    {"text": "The Eiffel Tower is located in Berlin.", "answer": "False"},
    {"text": "The Great Barrier Reef is located off the coast of Brazil.", "answer": "False"},
    {"text": "The chemical symbol for hydrogen is H.", "answer": "True"},
    {"text": "The capital of Germany is Munich.", "answer": "False"},
    {"text": "The Great Wall of China is over 20,000 kilometers long.", "answer": "True"},
    {"text": "The largest ocean on Earth is the Pacific Ocean.", "answer": "True"},
    {"text": "The capital of the United States is New York City.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The Great Wall of China is located in China.", "answer": "True"},
    {"text": "The currency of Japan is the Yen.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The largest continent by land area is Africa.", "answer": "False"},
    {"text": "The Great Wall of China is made of brick.", "answer": "True"},
    {"text": "The capital of Russia is St. Petersburg.", "answer": "False"},
    {"text": "The chemical symbol for water is H2O.", "answer": "True"},
    {"text": "The largest country in the world by population is China.", "answer": "True"},
    {"text": "The human body has 32 teeth.", "answer": "True"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"},
    {"text": "The Great Barrier Reef is located off the coast of Australia.", "answer": "True"},
    {"text": "The smallest country in the world is Vatican City.", "answer": "True"},
    {"text": "The Great Wall of China is located in Japan.", "answer": "False"},
    {"text": "The capital of Germany is Berlin.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The tallest building in the world is in Dubai.", "answer": "True"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "The Great Wall of China is made of ice.", "answer": "False"},
    {"text": "The largest country in the world by land area is Russia.", "answer": "True"},
    {"text": "The Great Barrier Reef is located in the Indian Ocean.", "answer": "False"},
    {"text": "The capital of Japan is Tokyo.", "answer": "True"},
    {"text": "The Great Wall of China is over 20,000 kilometers long.", "answer": "True"},
    {"text": "The largest ocean on Earth is the Atlantic Ocean.", "answer": "False"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The tallest mountain in the world is Mount Everest.", "answer": "True"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The Great Barrier Reef is located off the coast of Brazil.", "answer": "False"},
    {"text": "The chemical symbol for carbon is C.", "answer": "True"},
    {"text": "The capital of Italy is Rome.", "answer": "True"},
    {"text": "The largest continent by land area is Africa.", "answer": "False"},
    {"text": "The Great Wall of China is made of brick.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "The largest country in the world by population is China.", "answer": "True"},
    {"text": "The human body has 32 teeth.", "answer": "True"},
    {"text": "The Great Wall of China is located in China.", "answer": "True"},
    {"text": "The chemical symbol for hydrogen is H.", "answer": "True"},
    {"text": "The capital of Germany is Munich.", "answer": "False"},
    {"text": "The tallest building in the world is in New York City.", "answer": "False"},
    {"text": "The Great Barrier Reef is located off the coast of Australia.", "answer": "True"},
    {"text": "The smallest country in the world is Vatican City.", "answer": "True"},
    {"text": "The Great Wall of China is located in Japan.", "answer": "False"},
    {"text": "The capital of the United States is New York City.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The chemical symbol for water is H2O.", "answer": "True"},
    {"text": "The largest country in the world by land area is Russia.", "answer": "True"},
    {"text": "The Great Wall of China is made of ice.", "answer": "False"},
    {"text": "The capital of Japan is Tokyo.", "answer": "True"},
    {"text": "The tallest mountain in the world is Mount Everest.", "answer": "True"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The Great Barrier Reef is located in the Indian Ocean.", "answer": "False"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "The largest ocean on Earth is the Pacific Ocean.", "answer": "True"},
    {"text": "The Great Wall of China is over 20,000 kilometers long.", "answer": "True"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The largest continent by land area is Africa.", "answer": "False"},
    {"text": "The Great Wall of China is made of brick.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "The smallest country in the world is Vatican City.", "answer": "True"},
    {"text": "The human body has 32 teeth.", "answer": "True"},
    {"text": "The Great Wall of China is located in China.", "answer": "True"},
    {"text": "The tallest building in the world is in Dubai.", "answer": "True"}
]
    
